### ISSUE TITLE
Text parsing inconsistent with in-game text parsing.

### ISSUE THREAD

**Issue by ErezHajaj** [ShootMe/BabaIsYouEditor#2]
The following phrase is parsed by the BabaIsYouEditor but is not parsed by the in game parser:

"Baba on Hedge Facing Down is Left"

The game does not parse the "baba on hedge" and only considers "Hedge facing down is left",
but the editor parses the entire statement.

**Comment by ShootMe** [comment]
Yea, the parser I implemented was just a basic attempt at what the game does. There are a number of more complex phrases that don't quite match the game itself. I don't have any plans to try and improve the parser at this point, since it was more to get as close as possible with minimal effort.
