### ISSUE TITLE
Missing elements

### ISSUE THREAD

**Issue by Blank-sadface** [ShootMe/BabaIsYouEditor#5]
The level editor lacks some of the elements in game such as 'FIRE' and a bunch others, would they be added in a further update of the program?
![Elements](https://user-images.githubusercontent.com/59178717/71374740-85d24d00-2607-11ea-898f-d6156e1af3a9.PNG)

**Comment by ShootMe** [comment]
The level editor doesn't contain any assets. It reads everything from the game directory. So if you want to see those assets you have to copy them to your world as well. You can get more help in the #LevelIsMake channel in the Baba Is You Discord https://discord.gg/GGbUUse
