### ISSUE TITLE
Cant open world

### ISSUE THREAD

**Issue by eggshell97** [ShootMe/BabaIsYouEditor#7]
![Capture](https://user-images.githubusercontent.com/61627195/75610255-94dcec00-5add-11ea-9851-b82f7afbce17.PNG)

**Comment by eggshell97** [comment]
no idea what it means

**Comment by ShootMe** [comment]
Means a game object in the files is there more than once. This editor doesn't really work with the new Baba is You game files anymore, and I don't plan to update it since the new in game editor is almost complete.
